### ISSUE TITLE
upload and monitor

### ISSUE THREAD

**Issue by wildchun** [yunyizhi/clion-platformio-plus#1]
每次点击Upload and Monitor，需要把上一次的的关闭，如果能自动关闭就更好了，希望作者可以尝试增加这个功能。

**Comment by yunyizhi** [comment]
大致加了一下，[0.0.2.2](https://github.com/yunyizhi/clion-platformio-plus/releases/tag/untagged-7837daeaddcd0370ac16)。
你可以先试试这个版本，我还没有上架插件市场。

**Comment by wildchun** [comment]
> 

好的 谢谢

**Comment by yunyizhi** [comment]
其实已经审核过了，上架成功了，建议用插件市场的版本
