### ISSUE TITLE
[Request] Can you add “Build and Upload Filesystem Image” to “Pio Plus Tasks”（可以将 Build and Upload Filesystem Image 添加进 Pio Plus Tasks 吗）

### ISSUE THREAD

**Issue by ygxbnet** [yunyizhi/clion-platformio-plus#4]
I am using Clion to develop the function of SPIFFS for ESP32

You need to use PlatformIO to build and upload the Filesystem Image. Although you can use custom commands to achieve this function, I think it will be more convenient to add this shortcut operation to "Pio Plus Tasks".

I hope the author can take this suggestion into consideration

> 我在使用 Clion 开发 ESP32 的 SPIFFS 的功能
>
> 需要使用 PlatformIO 构建并上传 Filesystem Image，虽然可以用自定义命令实现这一功能，但我觉得如果把这一快捷操作加入到  Pio Plus Tasks 中会更方便操作。
>
> 希望作者大大可以采纳这个建议

#5  

---

Command（命令）：

```shell
run --target buildfs --target uploadfs
```
Example（示例）：

![image](https://github.com/yunyizhi/clion-platformio-plus/assets/87907576/259621dd-a553-4abf-845f-4d919ca9e71f)

**Comment by yunyizhi** [comment]
只有乐鑫的esp32 esp8266这些开发板可以使用 buildfs 和 uploadfs 这两个target。树上的List Targets 可以看每个env 支持的 target。我今后会考虑把pio 运行配置里面的任务 ，在树上放一个文件夹 这样可以加自定义命令到树上。

**Comment by ygxbnet** [comment]
嗯，OK，那我把 PR 给关了

**Comment by ygxbnet** [comment]
不过 `run --target buildfs --target uploadfs` 是把 `buildfs` 和 `uploadfs` 两个命令结合起来的

**Comment by ygxbnet** [comment]
不过还是谢谢作者了，这个插件还是非常好用的
