### ISSUE TITLE
latest build not on jetbrains site

### ISSUE THREAD

**Issue by TomW1605** [yunyizhi/clion-platformio-plus#8]
the latest build (0.0.71) here isnt on the jetbrains site and cant be installed through the plugin manager. the current build (0.0.70) dose not support clion 2024.2. could the build on the plugin site be updated?

**Comment by yunyizhi** [comment]
Install from Disk
![image](https://github.com/user-attachments/assets/8a4b4c8e-11db-4746-a0db-ef1cdf176457)

**Comment by TomW1605** [comment]
thanks

**Comment by yunyizhi** [comment]
Version 0.0.7.1-beta of the Platformio Plus plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/20232-platformio-plus/versions/stable/590267.
